import type { Metadata } from "next";
import "./globals.css";
import Menu from "@/Components/Header/Menu";
import Footer from "@/Components/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body>
        <Menu />
        {children}

        <Footer />
      </body>
    </html>
  );
}
